name       : perl-text-csv
version    : 0.5
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/E/ER/ERANGEL/Text-CSV-0.5.tar.gz : 10fdd12b321d75f7a357626afb91b37bc1bdc4ce355347cb5e14435da7845499
license    : Artistic-2.0
component  : programming.perl
summary    : Comma-separated values manipulation routines
description: |
    Comma-separated values manipulation routines
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
