name       : perl-text-csv
version    : '2.02'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/Text-CSV-2.02.tar.gz : 84120de3e10489ea8fbbb96411a340c32cafbe5cdff7dd9576b207081baa9d24
homepage   : https://metacpan.org/pod/Text::CSV
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Text::CSV - comma-separated values manipulator (using XS or PurePerl)
description: |
    Text::CSV is a thin wrapper for Text::CSV_XS-compatible modules now. All the backend modules provide facilities for the composition and decomposition of comma-separated values. Text::CSV uses Text::CSV_XS by default, and when Text::CSV_XS is not available, falls back on Text::CSV_PP, which is bundled in the same distribution as this module.
builddeps  :
    - perl-test-pod
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
