name       : perl-text-csv
version    : '1.95'
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/Text-CSV-1.95.tar.gz : 7e0a11d9c1129a55b68a26aa4b37c894279df255aa63ec8341d514ab848dbf61
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Comma-separated values manipulation routines
description: |
    Comma-separated values manipulation routines
builddeps  :
    - perl-test-pod
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
