name       : perl-text-csv
version    : '2.00'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/I/IS/ISHIGAKI/Text-CSV-2.00.tar.gz : 8ccbd9195805222d995844114d0e595bb24ce188f85284dbf256080311cbb2c2
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Comma-separated values manipulation routines
description: |
    Comma-separated values manipulation routines
builddeps  :
    - perl-test-pod
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
